### ISSUE TITLE
[REQ] Automatically select the current repo and branch if exist in Checkmarx One

### ISSUE THREAD

**Issue by baruchiro** [Checkmarx/ast-vscode-extension#296]
### Is your request related to a workflow problem?
When you first initializing the extension, in a new VSCode workspace, you need to select a project and branch from Checkmarx One.

Now, I think the idea of the extension is not just to be a general viewer for Checkmarx One, but to show the relevant results from Checkmarx One for your current work.

### Propose a solution
When the extension initialized, fetch the list of projects from Checkmarx One, and look for a project configured for the current local git repo. (I mean, the remote of the local repo).

After that, if found, set the current branch automatically, or the default branch if the current is not existing.

**Comment by pedrompflopes** [comment]
@baruchiro Thanks for raising this. 

@Yoavast Please review the request.

**Comment by Yoavast** [comment]
Thank you for your suggestion! That does sound like a good solution to ensure that the extension is able to show the relevant results from Checkmarx One for the user's current work.

One thing to consider is whether this solution would work for all use cases, or if there may be scenarios where the user wants to view results from a different project or branch. In those cases, it might be helpful to provide the user with the ability to manually select a different project or branch.

Overall, it seems like adding the option to automatically select the project and branch based on the current local git repository would be a useful feature for the extension.
