### ISSUE TITLE
[REQ] Start scan for another/new branch

### ISSUE THREAD

**Issue by baruchiro** [Checkmarx/ast-vscode-extension#297]
### Is your request related to a workflow problem?
1. Configure the extension with your project and `master` branch.
2. Checkout a new branch called `new-branch`.
3. Start a new scan from the extension.
4. You will get this: 
![image](https://user-images.githubusercontent.com/17686879/204262883-7515ecf6-a7b3-46d7-b0cd-602db3607e0c.png)

### Propose a solution
I think we should add an option to create a new scan for the new branch.

**Comment by pedrompflopes** [comment]
@baruchiro  Thanks for your question. 

In this case, if you select "Yes" it will create a new scan for "master" branch. @Yoavast Please check if it is something we can add to the backlog.

**Comment by baruchiro** [comment]
@pedrompflopes I know, I tried ;-)

But I'm looking for an option to start a new scan for the new branch (maybe it will require us to first push the branch).

**Comment by Yoavast** [comment]
Thank you for your suggestion! We agree that adding the option to create a new scan for a new branch is a good idea and can provide additional value to users of the extension.

We will add this feature request to our future roadmap. 
We appreciate your feedback and look forward to bringing this feature to the extension.
