### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by T0091YM** [Checkmarx/ast-vscode-extension#813]
Not able to configure the VS code extension for check Marx.

Getting errors while trying to bind to a project. PFA the screenshot for more details.
### Environment
- Vscode extension version v2.8.0
kindly check the issue and please let us know for any
![checkmarx-vscode_err](https://github.com/Checkmarx/ast-vscode-extension/assets/144135859/fd0b02d2-e6b4-4171-ad36-c4727b5cb2e1)
![checkmarx-vscode_err](https://github.com/Checkmarx/ast-vscode-extension/assets/144135859/ace42b44-f6b8-48d6-99ee-16b462b05eec)
 further details.

**Comment by OrShamirCM** [comment]
It can't reproduced.
Please update the Vscode extension and make sure you can connect to CxCli without the plugin too. If there are still issues, ensure Checkmark's IPs are whitelisted on your firewall or contact our support team. 
Thanks, Or
